project:
  type: website
  output-dir: ../docs

website:
  title: "CS 2731 Introduction to Natural Language Processing"
  navbar:
    left:
      - href: project.qmd
        text: Project
      - href: hw1.qmd
        text: HW1
      - href: hw2.qmd
        text: HW2
      - href: hw3.qmd
        text: HW3
      - href: hw4.qmd
        text: HW4

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



